# These are supported funding model platforms

github: #
patreon: #
open_collective: #
ko_fi: jonasstrehle
tidelift: #
community_bridge: #
liberapay: #
issuehunt: #
otechie: #
custom: ['buymeacoff.ee/jonasstrehle']
